Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

AllCops:
  DisplayCopNames: true
  Exclude:
    - 'spec/**/*'
    - 'Gemfile*'
    - '*.gemspec'

Documentation:
  Enabled: false
